kind: PersistentVolume
apiVersion: v1
metadata:
  name: sonar-pv0002
  namespace: sonarqube
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgresql/
